apiVersion: apps/v1
kind: Deployment
metadata:
  name: olm-operator
spec:
  template:
    spec:
      containers:
      - name: olm-operator
        args:
        - --namespace
        - $(POD_NAMESPACE)
        - --writeStatusName
        - operator-lifecycle-manager
        - --writePackageServerStatusName
        - operator-lifecycle-manager-packageserver
        - --tls-cert
        - /var/run/secrets/serving-cert/tls.crt
        - --tls-key
        - /var/run/secrets/serving-cert/tls.key
        env:
        - name: RELEASE_VERSION
          value: "0.0.1-snapshot"
        volumeMounts:
        - mountPath: /var/run/secrets/serving-cert
          name: serving-cert
      priorityClassName: "system-cluster-critical"
      volumes:
      - name: serving-cert
        secret:
          secretName: catalog-operator-serving-cert
      nodeSelector:
        beta.kubernetes.io/os: linux
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node.kubernetes.io/unreachable
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 120
      - key: node.kubernetes.io/not-ready
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 120
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-operator
spec:
  template:
    spec:
      containers:
      - name: catalog-operator
        args:
        - --namespace
        - openshift-marketplace
        - --writeStatusName
        - operator-lifecycle-manager-catalog
        - --tls-cert
        - /var/run/secrets/serving-cert/tls.crt
        - --tls-key
        - /var/run/secrets/serving-cert/tls.key
        env:
        - name: RELEASE_VERSION
          value: "0.0.1-snapshot"
        volumeMounts:
        - mountPath: /var/run/secrets/serving-cert
          name: serving-cert
      priorityClassName: "system-cluster-critical"
      volumes:
      - name: serving-cert
        secret:
          secretName: catalog-operator-serving-cert
      nodeSelector:
        beta.kubernetes.io/os: linux
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node.kubernetes.io/unreachable
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 120
      - key: node.kubernetes.io/not-ready
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 120
