apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: porcelain-server
  namespace: openshift-operator-lifecycle-manager
  labels:
    olm.version: 0.11.0
    olm.clusteroperator.name: operator-lifecycle-manager-porcelain-server
spec:
  displayName: Operator Porcelain Server
  description: Surfaces synthesized information
  minKubeVersion: 1.11.0
  keywords: ['installedoperators', 'installed', 'operators', 'olm']
  maintainers:
  - name: Red Hat
    email: openshift-operators@redhat.com
  provider:
    name: Red Hat
  links:
  - name: Operator Porcelain Server
    url: https://github.com/operator-framework/operator-lifecycle-manager/tree/master/pkg/porcelain-server
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: false
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: true
  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - serviceAccountName: olm-operator-serviceaccount
        rules:
        - apiGroups:
            - "" # core
          resources:
            - namespaces
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - authorization.k8s.io
          resources:
            - subjectaccessreviews
            - roles
            - rolebindings
          verbs:
            - create
            - get
            - list
            - watch
        - apiGroups:
          - "operators.coreos.com"
          resources:
          - clusterserviceversions
          - subscriptions
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - "porcelain.operators.coreos.com"
          resources:
          - installedoperators
          verbs:
          # TODO: rein in verb scope
          - "*"
      deployments:
      - name: porcelain-server
        spec:
          strategy:
            type: RollingUpdate
          replicas: 2
          selector:
            matchLabels:
              app: porcelain-server
          template:
            metadata:
              labels:
                app: porcelain-server
            spec:
              serviceAccountName: olm-operator-serviceaccount
              priorityClassName: "system-cluster-critical"
              nodeSelector:
                beta.kubernetes.io/os: linux
                node-role.kubernetes.io/master: ""
                
              tolerations:
              - effect: NoSchedule
                key: node-role.kubernetes.io/master
                operator: Exists
              - effect: NoExecute
                key: node.kubernetes.io/unreachable
                operator: Exists
                tolerationSeconds: 120
              - effect: NoExecute
                key: node.kubernetes.io/not-ready
                operator: Exists
                tolerationSeconds: 120
              
              containers:
              - name: porcelain-server
                command:
                - /bin/porcelain-server
                - -v=4
                - --secure-port
                - "5443"
                - --use-embedded-etcd
                image: quay.io/operator-framework/olm@sha256:81813ac9c937187c29e080c0975bb18489c1f232009c38c8d3a27bc9956ddd21
                imagePullPolicy: IfNotPresent
                ports:
                - containerPort: 5443
                livenessProbe:
                  httpGet:
                    scheme: HTTPS
                    path: /healthz
                    port: 5443
                readinessProbe:
                  httpGet:
                    scheme: HTTPS
                    path: /healthz
                    port: 5443
                terminationMessagePolicy: FallbackToLogsOnError
                resources:
                  requests:
                    cpu: 10m
                    memory: 50Mi
                  
                volumeMounts:
                - mountPath: /porcelain.etcd
                  name: etcd-cache
              volumes:
              - name: etcd-cache
                emptyDir:
                  medium: "Memory"
  maturity: alpha
  version: 0.11.0
  apiservicedefinitions:
    owned:
    - group: porcelain.operators.coreos.com
      version: v1alpha1
      kind: InstalledOperator
      name: installedoperators
      displayName: Installed Operator
      description: Represents the state of an installed operator.
      deploymentName: porcelain-server
      containerPort: 5443